name: question-service
services:
  question_db:
    container_name: question_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Password123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password123 -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  question_db.configurator:
    container_name: configurator
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    depends_on:
      question_db:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S question_db -U sa -P Password123 -d master -C -i docker-entrypoint-initdb.d/init.sql;
      /opt/mssql-tools18/bin/sqlcmd -S question_db -U sa -P Password123 -d master -C -i docker-entrypoint-initdb.d/example.sql;
      echo "All done!";
      '
volumes:
  mssql_data:
